### PR TITLE
13: Add MMRM forest plot functionality

### LINKED ISSUE #13: [tern.mmrm] Create forest plot functions for MMRM subgroup analyses
To do:

- [x] design doc
  - [x] Adjustments to `fit_mmrm()` / `get_mmrm_lsmeans()`
  	- [x] save the `averages_emmeans` list in the object
  	- [x] add the `weights_emmeans` chosen for LS means in the object
  - [x] LS means computations
      - [x] go via separate MMRM fits to compute the LS means for the subgroups
      - [x] works for factor variables used as such
      - [x] works for overlapping combination of factor levels
	  - [x] works for single visit
	  - [x] works for average of visits
  - [x] Extraction function
  - [x] Formatted analysis function
  - [x] Table creating function
- [x] create functions
- [ ] add to TLG-C

--
Original feedback:

FSTG01 layout example from GDSR as follow, with the following note of modification

* Please replace the column heading “Subgroup” with “Baseline Risk Factor”, remove the “Category” column and display the Category headings directly underneath the Baseline Risk Factor heading, as in FSTG01. Also, replace the first row heading, “Overall”, with “All Patients”, consistent with FSTG01
* By default present all summary statistics shown in the mockup. Allow the option for presenting p-value for each mean difference to the right of the 95% CI.  

image

Summary table can be obtained from `fit_mmrm`. 

Provenance: 
```
Creator: anajens
```

### PR DESCRIPTION
**Pull request by danielinteractive**
closes #13

### CODE REVIEW

**Comment by danielinteractive** [comment]
@juliadedic1 if you could have a look at the design doc for the MMRM forest plot and see if that works for you it would be cool. Results is something like this:

image

which is in line what we have with other forest plots in `tern`.

**Comment by danielinteractive** [comment]
@shajoezhu any chance you could review this today?

**Comment by shajoezhu** [comment]
Installing with 

```
remotes::install_github(   
      "insightsengineering/tern.mmrm",
    upgrade = "never",
    ref = "13_mmrm_forest@pre-release",
    lib = mmrm_lib,
    force = TRUE,
    build_vignettes = FALSE
)
```

**Review by shajoezhu — APPROVED** [review]
Thanks @danielinteractive , lgtm! install fine, and code works well.

**Comment by danielinteractive** [comment]
Great thanks @shajoezhu

**Pull request merged**
