### PR TITLE
Bumps `{rmarkdown}` minimal version

### PR DESCRIPTION
**Pull request by averissimo**
# Pull Request

Part of https://github.com/insightsengineering/coredev-tasks/issues/546

Necessary bump to overcome a lack of binary on ppm snapshots that causes an error on minimum strategies for `scheduled` workflows.

### CODE REVIEW

**Comment by averissimo** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by averissimo** [comment]
All `verdepcheck` strategies pass: https://github.com/insightsengineering/tern.mmrm/actions/runs/9398825847

I also fixed 2 broken URLs

**Comment by averissimo** [comment]
There's a problem with `fontspec` argument from `rtables` / `formatter`, researching it and bringing this back to draft

**Comment by averissimo** [comment]
All good now: https://github.com/insightsengineering/tern.mmrm/actions/runs/9450170926

**Review by m7pr — APPROVED** [review]

**Pull request merged**
