### PR TITLE
options for strict tests; few enhancements

### PR DESCRIPTION
**Pull request by pawelru**
- part of https://github.com/insightsengineering/coredev-tasks/issues/478
  - please read this for more info about the implementation: https://github.com/insightsengineering/coredev-tasks/issues/478#issuecomment-1909912778
- added skip if not installed for suggested package that I discovered locally

### CODE REVIEW

**Review by danielinteractive — APPROVED** [review]
thanks @pawelru

**Comment by danielinteractive** [comment]
@pawelru hm quick question though.... when I just ran `tern.mmrm` tests locally, and I guess the new setup applies, I get this (and many more of the same):

```
Warning (test-table_mmrmt01.R:45:3): Fixed effects table is produced correctly
partial argument match of 'val' to 'vals'
Backtrace:
     ▆
  1. ├─tern::as.rtable(mmrm_results, type = "fixed", format = "xx.xx") at test-table_mmrmt01.R:45:3
  2. └─tern.mmrm:::as.rtable.tern_mmrm(...)
  3.   └─tern.mmrm::h_mmrm_fixed(x, ...) at tern.mmrm/R/tabulate_mmrm.R:58:3
  4.     ├─tern::as.rtable(fixed_table[, pvalue_column, drop = FALSE], format = "x.xxxx | (<0.0001)") at tern.mmrm/R/tabulate_mmrm.R:72:3
  5.     └─tern:::as.rtable.data.frame(...)
  6.       ├─base::do.call(...)
  7.       └─base::Map(...)
  8.         └─base::mapply(FUN = f, ..., SIMPLIFY = FALSE)
  9.           └─tern (local) `<fn>`(row = dots[[1L]][[10L]], row_name = dots[[2L]][[10L]])
 10.             ├─base::do.call(rrow, c(as.list(unname(row)), row.name = row_name))
 11.             └─rtables (local) `<fn>`(0.851692307948709, row.name = "ARMCDTRT:AVISITVIS4")
 12.               └─rtables::DataRow(...)
```

Is this from the new options?

If yes I guess this is an issue in `rtables` ?... @shajoezhu fyi

**Comment by danielinteractive** [comment]
ah ok :D I thought this is ready already for merge... hm no worries

**Comment by pawelru** [comment]
This should have probably merged in sequence with rtables being first. Sorry about that. 
In case it's a blocker - please just temporarily modify the condition to be always false so that the options won't be set.
Everything will be back clean again once we merge aforementioned PR.

**Comment by danielinteractive** [comment]
since we run checks here with `--as-cran` we don't use the settings on CI, so should be ok for now

**Comment by shajoezhu** [comment]
hi guys, sorry, we were busy on tmc release, so i put a hold on including those changes in all sme packages until tmc cran releases completion

**Pull request merged**
