### PR TITLE
85: cleanup `tern.mmrm` 

### LINKED ISSUE #85: correct required package versions
To do:

- [x] `emmeans` at least 1.6
- [x] `testthat` at least 3.1.0
- [x] `mmrm` at least 0.0.0.9006

### PR DESCRIPTION
**Pull request by danielinteractive**
closes #85 and #60

### CODE REVIEW

**Comment by danielinteractive** [comment]
@shajoezhu can maybe SME help to review this? really just cleanup

**Comment by dinakar29** [comment]
@danielinteractive Instead of storing the `lifecycle` badges in the `man/figures` directory, you can use https://shields.io/ instead. They follow this pattern: `https://img.shields.io/badge/lifecycle-<status>-<color>`

Examples:

`https://img.shields.io/badge/lifecycle-stable-brightgreen`  is https://img.shields.io/badge/lifecycle-stable-green

**Comment by danielinteractive** [comment]
> @danielinteractive Instead of storing the `lifecycle` badges in the `man/figures` directory, you can use [shields.io](https://shields.io/) instead.

Thanks @dinakar29 , I think I am sticking to standard `usethis::use_lifecycle()` behavior for now for simplicity. (Maybe would be good to change it there?)

**Comment by dinakar29** [comment]
> usethis



> > @danielinteractive Instead of storing the `lifecycle` badges in the `man/figures` directory, you can use [shields.io](https://shields.io/) instead.
> 
> Thanks @dinakar29 , I think I am sticking to standard `usethis::use_lifecycle()` behavior for now for simplicity. (Maybe would be good to change it there?)

They themselves use shields.io: https://github.com/r-lib/usethis/blob/main/R/badge.R#L101 and do not save to disk. Saving to disk will bloat your package size unnecessarily. Matter of fact, the way they do it is exactly right - where they generate the md snippet and copy it to the clipboard:

```R
> usethis::use_lifecycle_badge("stable")
• Copy and paste the following lines into 'README.md':
  <!-- badges: start -->
  [![Lifecycle: stable](https://img.shields.io/badge/lifecycle-stable-brightgreen.svg)](https://lifecycle.r-lib.org/articles/stages.html#stable)
  <!-- badges: end -->
  [Copied to clipboard]
```

**Comment by danielinteractive** [comment]
thanks @dinakar29 , ok, maybe then this would be something for core team to cleanup across all repos? @pawelru

**Comment by pawelru** [comment]
> thanks @dinakar29 , ok, maybe then this would be something for core team to cleanup across all repos? @pawelru

Actually it's needed for roxygen as it refers to a file in `figures/` directory.

```
#' @description `r lifecycle::badge("stable")`
``` 

above line in `.R` file will be translated into:

```
\ifelse{html}{\href{https://lifecycle.r-lib.org/articles/stages.html#stable}{\figure{lifecycle-stable.svg}{options: alt='[Stable]'}}}{\strong{[Stable]}}
```

Without those files in repo we would have the following https://github.com/insightsengineering/coredev-tasks/issues/133

**Pull request merged**
