### PR TITLE
2: Add averages of visits to `fit_mmrm` and downstream tables.

### LINKED ISSUE #2: [tern.mmrm] MMRM table using average of visits
Objective: Know how to program with `tern.mmrm` (and possible extensions we should then put in there) MMRM table using average of visits, as shown in plot below.
image (6)

Note: The average of visits here is not from the average of values calculated in datasets, but it is coming from a lsmestimate statement from proc mixed model in SAS.
image

To do:

- [x] Read up in the SAS manual (and save link) on `lsmestimate` options: https://documentation.sas.com/doc/en/pgmsascdc/9.4_3.4/statug/statug_introcom_sect049.htm
- [x] Translate the calculation to `emmeans` used in `tern.mmrm`
- [x] Alternative path is to directly specify coefficients for linear combination of visits, compare with Julia/Gonzalo's code:
	- [x] https://github.roche.com/duranpag/Ophtha_MMRM_R_assess
	- [x] QC of results: https://github.roche.com/dedicj/mmrm_nlme_glmmTMB
- [x] See https://github.com/insightsengineering/tern.mmrm/blob/c0d3c4bd944a2b185299cd046cddaddff95b5336/design/design_satterthwaite_df.Rmd#L226 how to use `emmeans()` for averages of visits
- [x] change existing `tern.mmrm` functions or results so that we can do this flexibly
	- [x] Add new argument `averages_emmeans` to `fit_mmrm()`
	- [x] Add helpers
        - [x] make them work without arm variable
	- [x] Passed to new argument `averages` of `get_mmrm_lsmeans()`
- [x] Adapt tests
	- [x] `fit_mmrm()`
	- [x] `get_mmrm_lsmeans()`

### PR DESCRIPTION
**Pull request by danielinteractive**
closes #2

### CODE REVIEW

**Review by juliadedic1 — COMMENTED** [review]
I tried it out with study data and I got this error coming from the `averages_emmeans` argument: `Error in colMeans(do.call(rbind, specs$coefs[averaged_indices])) : 'x' must be an array of at least two dimensions`. Here's my code: `mmrm <- fit_mmrm(
  vars = list(
    response = "CHG",
    visit = "AVISIT",
    arm = "TRT01P",
    covariates = c("STRAT1", "STRAT2", "STRAT3"),
    id = "USUBJID"
  ),
  data = adoe_filtered,
  averages_emmeans = list(
    "average of Week 40 & 44" = c("Week 40", "Week 44")
  ),
  cor_struct = "random-quadratic"
) `

**Comment by danielinteractive** [comment]
Ok thanks @juliadedic1 can you please share your script and data with me such that I can debug this? Thanks

**Comment by juliadedic1** [comment]
@danielinteractive I sent you an email with the script. You should have access to the data now. Thanks!

**Review by juliadedic1 — APPROVED** [review]
This works beautifully now! Thanks :D

**Pull request merged**
