### PR TITLE
fix unit test (which otherwise fails with upcoming mmrm CRAN release)

### PR DESCRIPTION
**Pull request by danielinteractive**
This is needed for https://github.com/openpharma/mmrm/issues/469

@shajoezhu do you think you can make a new CRAN release of `tern.mmrm` these days? 😃

### CODE REVIEW

**Comment by danielinteractive** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by shajoezhu — APPROVED** [review]
lgtm! thanks @danielinteractive

**Comment by shajoezhu** [comment]
> @shajoezhu do you think you can make a new CRAN release of `tern.mmrm` these days? 😃

Hi @danielinteractive , yes, definitely. We are in the release cycle at the moment as well. We were preparing for a new release for tern (formatters, and rtables just cran released last week). Just wondering what is your time line for mmrm? We can definitely support this, and make a new cran release for tern.mmrm

**Comment by danielinteractive** [comment]
Thanks @shajoezhu , perfect, it would be great if you could release `tern.mmrm` in the next few days, such that we can release `mmrm` as soon as possible - then we won't get failures on the reverse dependency check from CRAN.

**Pull request merged**
